plus

diff --git a/.github/workflows/integrate-ecs.yml b/.github/workflows/integrate-ecs.yml
--- a/.github/workflows/integrate-ecs.yml
+++ b/.github/workflows/integrate-ecs.yml
@@ -28,63 +28,63 @@ jobs:
     runs-on: self-hosted
     outputs:
       image: ${{ steps.build-web.outputs.image }}
-    # steps:
-    #   - name: Checkout
-    #     uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
-    #   - name: Configure AWS credentials
-    #     uses: ./.github/actions/aws-config
-    #     with:
-    #       aws-access-key-id: ${{ env.AWS_DEPLOY_ACCESS_KEY_ID }}
-    #       aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET_ACCESS_KEY }}
-    #       aws-region: ${{ env.AWS_REGION }}
-    #       ecr-registry: ${{ env.ECR_REGISTRY }}
+      - name: Configure AWS credentials
+        uses: ./.github/actions/aws-config
+        with:
+          aws-access-key-id: ${{ env.AWS_DEPLOY_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+          ecr-registry: ${{ env.ECR_REGISTRY }}
 
-    #   - name: Build Web
-    #     id: build-web
-    #     uses: ./.github/actions/build-web
-    #     with:
-    #       image: "${{ env.WEB_IMAGE }}:${{ github.sha }}"
+      - name: Build Web
+        id: build-web
+        uses: ./.github/actions/build-web
+        with:
+          image: "${{ env.WEB_IMAGE }}:${{ github.sha }}"
 
-    #   - name: Ensure Build Web Success
-    #     if: ${{ failure() }}
-    #     run: |
-    #       echo "Build Web failed. Exiting workflow."
-    #       exit 1
+      - name: Ensure Build Web Success
+        if: ${{ failure() }}
+        run: |
+          echo "Build Web failed. Exiting workflow."
+          exit 1
 
   deploy:
     name: Deploy to ECS
     runs-on: self-hosted
     needs: [build-web]
     if: ${{ success() }}
-    # steps:
-    #   - name: Checkout code
-    #     uses: actions/checkout@v2
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    #   - name: Configure AWS credentials
-    #     uses: ./.github/actions/aws-config
-    #     with:
-    #       aws-access-key-id: ${{ env.AWS_DEPLOY_ACCESS_KEY_ID }}
-    #       aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET_ACCESS_KEY }}
-    #       aws-region: ${{ env.AWS_REGION }}
-    #       ecr-registry: ${{ env.ECR_REGISTRY }}
+      - name: Configure AWS credentials
+        uses: ./.github/actions/aws-config
+        with:
+          aws-access-key-id: ${{ env.AWS_DEPLOY_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+          ecr-registry: ${{ env.ECR_REGISTRY }}
 
-    #   - name: Fill in the new image ID for web container
-    #     id: web-task-def
-    #     uses: aws-actions/amazon-ecs-render-task-definition@v1
-    #     with:
-    #       task-definition: ${{ env.ECS_TASK_DEFINITION }}
-    #       container-name: ${{ env.WEB_CONTAINER_NAME }}
-    #       image: "${{ env.WEB_IMAGE }}:${{ github.sha }}"
+      - name: Fill in the new image ID for web container
+        id: web-task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: ${{ env.ECS_TASK_DEFINITION }}
+          container-name: ${{ env.WEB_CONTAINER_NAME }}
+          image: "${{ env.WEB_IMAGE }}:${{ github.sha }}"
 
-    #   - name: Run migration
-    #     run: docker run --rm ${{ env.WEB_IMAGE }}:${{ github.sha }} --verbose
-    #     continue-on-error: true
+      - name: Run migration
+        run: docker run --rm ${{ env.WEB_IMAGE }}:${{ github.sha }} --verbose
+        continue-on-error: true
         
-    #   - name: Deploy to Amazon ECS service
-    #     uses: aws-actions/amazon-ecs-deploy-task-definition@v2
-    #     with:
-    #       task-definition: ${{ steps.web-task-def.outputs.task-definition }}
-    #       service: ${{ env.ECS_SERVICE }}
-    #       cluster: ${{ env.ECS_CLUSTER }}
-    #       wait-for-service-stability: true
+      - name: Deploy to Amazon ECS service
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
+        with:
+          task-definition: ${{ steps.web-task-def.outputs.task-definition }}
+          service: ${{ env.ECS_SERVICE }}
+          cluster: ${{ env.ECS_CLUSTER }}
+          wait-for-service-stability: true
